### ISSUE TITLE
IsConnected returns false or nothing

### ISSUE THREAD

**Issue by njaksch** [dexsper/RustRcon#2]
I've established a connection to a rust server.
I can retrieve the server name like mentioned in the examples but IsConnected will return false.
`
Log.Info(null, rcon.IsConnected.ToString());
rcon.SendCommand(new GetServerInfo(x =>
{
    Log.Info(GetType().ToString(), $"Connected to: {x.Hostname}");
}));
Log.Info(null, rcon.IsConnected.ToString());
`
The output looks like that:
`
False
Connected to: Testserver
False
`
Furthermore if you provide wrong server credentials you won't get any output as it seems.
This makes it very hard to check if the rcon is actually connected.

**Comment by dexsper** [comment]
Fixed in https://github.com/dexsper/RustRcon/commit/2683d9236bd4b7d14afae51fd3b1ffbb3f5aa2af

The logic is that the connection will be open indefinitely until the data sending fails (or a system timeout occurs, if it is configured at all).
And the fact that after the error about socket closing the State - Open hangs is not logical at all, but you need to understand what it [means](https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets.websocketstate?view=net-8.0).

I used to rely on [websocket-sharp](https://github.com/sta/websocket-sharp) library which I used for web sockets - I thought it would track state, I was young and stupid 😪
